### ISSUE TITLE
npm throws error when running locally

### ISSUE THREAD

**Issue by AndrewCash** [3513-snacc/RegisterWeb-NodeJS#4]
Console output:

npm run start

> registerweb@0.0.1 start /Users/andrewcash/code/SoftwareEngineering/TeamRepo/RegisterWeb-NodeJS
> node dist/server.js

{ Url: [Function: Url],
  parse: [Function: urlParse],
  resolve: [Function: urlResolve],
  resolveObject: [Function: urlResolveObject],
  format: [Function: urlFormat],
  URL: [Function: URL],
  URLSearchParams: [Function: URLSearchParams],
  domainToASCII: [Function: domainToASCII],
  domainToUnicode: [Function: domainToUnicode],
  pathToFileURL: [Function: pathToFileURL],
  fileURLToPath: [Function: fileURLToPath] }
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Url.parse (url.js:151:3)
    at Object.urlParse [as parse] (url.js:146:13)
    at new Sequelize (/Users/andrewcash/code/SoftwareEngineering/TeamRepo/RegisterWeb-NodeJS/node_modules/sequelize/lib/sequelize.js:117:28)
    at Object.<anonymous> (/Users/andrewcash/code/SoftwareEngineering/TeamRepo/RegisterWeb-NodeJS/dist/controllers/commands/models/databaseConnection.js:8:30)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/andrewcash/code/SoftwareEngineering/TeamRepo/RegisterWeb-NodeJS/dist/controllers/commands/models/entities/productEntity.js:7:30)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/andrewcash/code/SoftwareEngineering/TeamRepo/RegisterWeb-NodeJS/dist/controllers/commands/models/repositories/productRepository.js:4:25)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! registerweb@0.0.1 start: `node dist/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the registerweb@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by AndrewCash** [comment]
Postgres database was not pointing to a url.

This was fixed by running the command:
export DATABASE_URL=postgres://localhost:5200
